/* Auto-generated by genmsg_cpp for file /home/masaru/fuerte_workspace/sandbox/usarsim/usarsim_inf/msg/RangeImageScan.msg */
#ifndef USARSIM_INF_MESSAGE_RANGEIMAGESCAN_H
#define USARSIM_INF_MESSAGE_RANGEIMAGESCAN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace usarsim_inf
{
template <class ContainerAllocator>
struct RangeImageScan_ {
  typedef RangeImageScan_<ContainerAllocator> Type;

  RangeImageScan_()
  : header()
  , dummy_param(0)
  {
  }

  RangeImageScan_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , dummy_param(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _dummy_param_type;
  uint8_t dummy_param;


  typedef boost::shared_ptr< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usarsim_inf::RangeImageScan_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RangeImageScan
typedef  ::usarsim_inf::RangeImageScan_<std::allocator<void> > RangeImageScan;

typedef boost::shared_ptr< ::usarsim_inf::RangeImageScan> RangeImageScanPtr;
typedef boost::shared_ptr< ::usarsim_inf::RangeImageScan const> RangeImageScanConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::usarsim_inf::RangeImageScan_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::usarsim_inf::RangeImageScan_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace usarsim_inf

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::usarsim_inf::RangeImageScan_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c8ee61fc395f79ed39913d793b03a68";
  }

  static const char* value(const  ::usarsim_inf::RangeImageScan_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2c8ee61fc395f79eULL;
  static const uint64_t static_value2 = 0xd39913d793b03a68ULL;
};

template<class ContainerAllocator>
struct DataType< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "usarsim_inf/RangeImageScan";
  }

  static const char* value(const  ::usarsim_inf::RangeImageScan_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint8 dummy_param\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::usarsim_inf::RangeImageScan_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::usarsim_inf::RangeImageScan_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::usarsim_inf::RangeImageScan_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::usarsim_inf::RangeImageScan_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.dummy_param);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RangeImageScan_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usarsim_inf::RangeImageScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::usarsim_inf::RangeImageScan_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dummy_param: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dummy_param);
  }
};


} // namespace message_operations
} // namespace ros

#endif // USARSIM_INF_MESSAGE_RANGEIMAGESCAN_H

