"""autogenerated by genpy from usarsim_inf/ToolchangerStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import usarsim_inf.msg
import std_msgs.msg

class ToolchangerStatus(genpy.Message):
  _md5sum = "8b5a06cc589e1ab2b44a5eec0fd708b9"
  _type = "usarsim_inf/ToolchangerStatus"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
EffectorStatus effector_status
ToolType tool_type

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: usarsim_inf/EffectorStatus
Header header
uint8 state
uint8 OPEN=0
uint8 CLOSE=1

================================================================================
MSG: usarsim_inf/ToolType
uint8 type
uint8 UNKNOWN=0
uint8 GRIPPER=1
uint8 VACUUM=2
uint8 TOOLCHANGER=3

"""
  __slots__ = ['header','effector_status','tool_type']
  _slot_types = ['std_msgs/Header','usarsim_inf/EffectorStatus','usarsim_inf/ToolType']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,effector_status,tool_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ToolchangerStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.effector_status is None:
        self.effector_status = usarsim_inf.msg.EffectorStatus()
      if self.tool_type is None:
        self.tool_type = usarsim_inf.msg.ToolType()
    else:
      self.header = std_msgs.msg.Header()
      self.effector_status = usarsim_inf.msg.EffectorStatus()
      self.tool_type = usarsim_inf.msg.ToolType()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.effector_status.header.seq, _x.effector_status.header.stamp.secs, _x.effector_status.header.stamp.nsecs))
      _x = self.effector_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2B.pack(_x.effector_status.state, _x.tool_type.type))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.effector_status is None:
        self.effector_status = usarsim_inf.msg.EffectorStatus()
      if self.tool_type is None:
        self.tool_type = usarsim_inf.msg.ToolType()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.effector_status.header.seq, _x.effector_status.header.stamp.secs, _x.effector_status.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.effector_status.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.effector_status.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.effector_status.state, _x.tool_type.type,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.effector_status.header.seq, _x.effector_status.header.stamp.secs, _x.effector_status.header.stamp.nsecs))
      _x = self.effector_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2B.pack(_x.effector_status.state, _x.tool_type.type))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.effector_status is None:
        self.effector_status = usarsim_inf.msg.EffectorStatus()
      if self.tool_type is None:
        self.tool_type = usarsim_inf.msg.ToolType()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.effector_status.header.seq, _x.effector_status.header.stamp.secs, _x.effector_status.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.effector_status.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.effector_status.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.effector_status.state, _x.tool_type.type,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_2B = struct.Struct("<2B")
